### ISSUE TITLE
"AttributeError: 'MSSQLInstance' object has no attribute 'port'"

### ISSUE THREAD

**Issue by jsdhasfedssad** [CompassSecurity/mssqlrelay#1]
Hi,

Thank you for this tool. I can see a lot of potential.

During testing of this tool I encountered the error below using the `checkall` parameter but not when using the `check` parameter. Any idea what the problem may be?
![mssql1](https://github.com/CompassSecurity/mssqlrelay/assets/97032878/d8d8f574-b6d6-456d-9c91-a67f979299d5)

**Comment by sploutchy** [comment]
Hi @jsdhasfedssad ,
Thanks for trying the tool. Apparently I made a change that broke this functionality before pushing to this repo.
I'll have to check this out. Sorry for the inconvenience. I'll let you know when it's fixed.
Cheers

**Comment by sploutchy** [comment]
Fixed by https://github.com/CompassSecurity/mssqlrelay/commit/5b9bccb057379894df8c09e3fe30586e51933757
